[theme]

# Primary accent for interactive elements
primaryColor = '#1f2226'

# Background color for the main content area
backgroundColor = '#191b1e'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#272b2f'

# Color used for almost all text
textColor = '#d0f0c0'